name: Build and Publish

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 
        uses: actions/setup-java@v4
        with:
          java-version: '21' 
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-artifact
          path: build/libs/*.jar

  publish:
    name: Publish to Releases
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: release
      url: https://github.com/${{ github.repository }}/releases
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: mod-artifact
          path: release-files

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
          files: release-files/*.jar
          draft: true
          generate_release_notes: true
          discussion_category_name: "Announcements"