name: Code Formatting & Validation

on:
  workflow_dispatch: # 仅手动触发

permissions:
  contents: write

jobs:
  code-formatting:
    name: Format Code
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      JAVA_VERSION: 21
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      # 关键修复点：显式设置文件权限
      - name: Fix executable permissions
        run: |
          chmod +x gradlew
          git config --global core.fileMode true

      - name: Setup JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', 'gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Execute code formatting
        run: ./gradlew spotlessApply

      - name: Check formatting consistency
        run: ./gradlew spotlessCheck

      - name: Detect formatted changes
        id: changes
        run: |
          echo "changed=$(git diff --name-only -- 'src/*.java' '*.gradle' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Commit formatting changes
        if: steps.changes.outputs.changed != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/*.java *.gradle
          git commit -m "style: Auto-format code [skip ci]" || echo "No changes to commit"
          git push origin HEAD:dev

      - name: Post cleanup
        if: always()
        run: |
          ./gradlew --stop
          rm -rf ~/.gradle/caches/build-cache-*